name: Build binary wheels
# Build wheels for various platforms and Python versions,
# optionally upload them to pypi

on:
  push:
jobs:

  wheels:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2019
        python:
          - 3.11
        include:
          # Usually set to ''
          - container:
            manylinux:
          # But overridden on Ubuntu
          - os: ubuntu-latest
            container: quay.io/pypa/manylinux_2_28_x86_64  # manylinux2014 is too old for actions/checkout to run on
            manylinux: 2_28
    uses: ./.github/workflows/buildwheel.yml
    with:
      python-version: ${{ !contains(matrix.container, 'manylinux') && matrix.python || '' }}   # do not run setup-python on manylinux
      python-interpreter: ${{ matrix.manylinux && format('python{0}', matrix.python) || 'python3' }}
      runs-on: ${{ matrix.os }}
      container: ${{ matrix.container }}
      manylinux-glibc-version: ${{ matrix.manylinux }}
      artifact-name: ${{ matrix.manylinux && 'manylinux' || matrix.os}}_${{ matrix.python }}
      cache: binaries

  gather:
    runs-on: ubuntu-latest
    needs: wheels
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: |
          ls -lR artifacts
          rm -f artifacts/windows*/*.tar.gz
          sources=(artifacts/*/*.tar.gz)
          wheels=(artifacts/*/*.whl)
          mkdir gathered
          mv "${sources[0]}" "${wheels[@]}" gathered
          ls -lR gathered

      - uses: actions/upload-artifact@v4
        with:
          path: gathered
          name: all-wheels

