name: Build binary wheels
# Build wheels for various platforms and Python versions,
# optionally upload them to pypi

on:
  push:

jobs:

  preflight:
    runs-on: ubuntu-latest
    outputs:
      sdist-hash: ${{ steps.hash.outputs.sdist-hash }}
    steps:

      - uses: actions/checkout@v4

      - id: pickcachehash
        # prints 'hash=0FABC...'
        run: |
          python3 scripts/hash-source.py >>$GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache
        with:
          path: dist
          key: cache-42-${{ steps.pickcachehash.outputs.hash }}

      - id: install
        if: (!steps.cache.outputs.cache-hit)
        uses: ./actions/install-correct-monetdb-version

      - name: Run tests
        if: (!steps.cache.outputs.cache-hit)
        env:
          MONETDBE_INCLUDE_PATH: ${{ steps.install.outputs.includedir }}
          MONETDBE_LIBRARY_PATH: ${{ steps.install.outputs.libdir }}
        run: |
          pip install --upgrade pip
          echo '========'
          pip install -e '.[test]'
          pytest -v

      - name: Build sdist
        if: (!steps.cache.outputs.cache-hit)
        env:
          MONETDBE_INCLUDE_PATH: ${{ steps.install.outputs.includedir }}
          MONETDBE_LIBRARY_PATH: ${{ steps.install.outputs.libdir }}
        run: |
          pip install --upgrade build
          python3 -m build --sdist
          ls dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 3

      - name: Hash sdist
        id: hash
        run: python3 scripts/hash-sdist.py dist/*.tar.gz
