name: Build binary wheels
# Build wheels for various platforms and Python versions,
# optionally upload them to pypi

on:
  push:

jobs:

  # Run the tests and upload an sdist
  preflight:
    runs-on: ubuntu-latest
    outputs:
      sdist-hash: ${{ steps.hash.outputs.sdist-hash }}
      # This is where you configure which Pythons to build for. Make sure to
      # quote them, we don't want to round version 3.10 to float 3.1!
      pythons: '[ "3.13", "3.12", "3.11", "3.10", "3.9", "3.8" ]'
    steps:

      - uses: actions/checkout@v4

      - id: pickcachehash
        # prints 'hash=0FABC...'
        run: |
          python3 scripts/hash-source.py >>$GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache
        with:
          path: dist
          key: cache-42-${{ steps.pickcachehash.outputs.hash }}

      - id: install
        if: (!steps.cache.outputs.cache-hit)
        uses: ./actions/install-correct-monetdb-version

      - name: Run tests
        if: (!steps.cache.outputs.cache-hit)
        env:
          MONETDBE_INCLUDE_PATH: ${{ steps.install.outputs.includedir }}
          MONETDBE_LIBRARY_PATH: ${{ steps.install.outputs.libdir }}
        run: |
          pip install --upgrade pip
          echo '========'
          pip install -e '.[test]'
          pytest -v

      - name: Build sdist
        if: (!steps.cache.outputs.cache-hit)
        env:
          MONETDBE_INCLUDE_PATH: ${{ steps.install.outputs.includedir }}
          MONETDBE_LIBRARY_PATH: ${{ steps.install.outputs.libdir }}
        run: |
          pip install --upgrade build
          python3 -m build --sdist
          ls dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 3

      - name: Hash sdist
        id: hash
        run: python3 scripts/hash-sdist.py dist/*.tar.gz


  # Use the manylinux container to ensure it works with old glibc versions.
  # Manylinux comes with all relevant Python versions preinstalled.
  linux:
    strategy:
      matrix:
        python: ${{ fromJSON(needs.preflight.outputs.pythons) }}
    needs: preflight
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    steps:

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: sdist

      - id: pickcachehash
        # prints 'sdist-hash=0F1234'
        run: |
          python3 scripts/hash-sdist.py sdist/*.tar.gz >>$GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache
        with:
          path: wheels
          key: cache-42-manylinux${{ matrix.python }}-${{ steps.pickcachehash.outputs.sdist-hash }}-${{ hashFiles('scripts/do-everything.py')}}
  
      - uses: ./actions/install-correct-monetdb-version
        if: (!steps.cache.outputs.cache-hit)
        id: installmonet

      - name: Build wheel
        if: (!steps.cache.outputs.cache-hit)
        run: |
          python${{ matrix.python }} scripts/do-everything.py \
            -s sdist/*.tar.gz \
            -d wheels \
            --wheel \
            --manylinux=2.28 \
            --inc-dir="${{ steps.installmonet.outputs.includedir }}" \
            --lib-dir="${{ steps.installmonet.outputs.libdir }}"

      - uses: actions/upload-artifact@v4
        with:
          name: manylinux-${{ matrix.python }}
          path: wheels/*.whl



