name: Build binary wheels
# Build wheels for various platforms and Python versions,
# optionally upload them to pypi

on:
  push:
jobs:

  wheels:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2019
        python:
          - 3.11
        include:
          - container:
            name:
          #### uncomment this to run in manylinux (doesn't work very well yet)
          # - os: ubuntu-latest
          #   container: quay.io/pypa/manylinux_2_28_x86_64
          #   name: manylinux
    uses: ./.github/workflows/buildwheel.yml
    with:
      python_version: ${{ matrix.python }}
      runs-on: ${{ matrix.os }}
      container: ${{ matrix.container }}
      #container: quay.io/pypa/manylinux_2_28_x86_64
      artifact-name: ${{ matrix.name || matrix.os }}_${{ matrix.python }}
      cache: binaries

  gather:
    runs-on: ubuntu-latest
    needs: wheels
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: |
          ls -lR artifacts
          sources=(artifacts/*/*.tar.gz)
          wheels=(artifacts/*/*.whl)
          mkdir gathered
          mv "${sources[1]}" "${wheels[@]}" gathered

      - uses: actions/upload-artifact@v4
        with:
          path: gathered
          name: all-wheels



